spring.application.name=noticia-certa-bot

# --- Configuração do Bot do Telegram ---
telegram.bot.username=NoticiaCertaBot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# --- Configuração do Banco de Dados (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5433/noticiacerta_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuração JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- Configuração do RabbitMQ ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
